name: Deploy to Production

on:
  release:
    types: [released]

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest

    env:
      DOCKER_REGISTRY: ${{ vars.PROD_DOCKER_REGISTRY }}
      ROLE_ARN: ${{ vars.PROD_DEPLOY_ROLE_ARN }}
      ENV_VARIABLES: ${{ vars.ENV_PROD }}

      AWS_DEFAULT_REGION: ap-southeast-1
      ENVIRONMENT: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get release version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          role-session-name: public-web-revamp-DeployRole
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin ${DOCKER_REGISTRY}

      - name: Set up environment variables
        run: |
          echo "${{ env.ENV_VARIABLES }}" > .env

      - name: Build and push Docker image
        run: |
          # Build and tag with both latest and the specific release version
          docker build --platform=linux/amd64 -t public-web-revamp:latest .

          # Tag
          docker tag public-web-revamp:latest ${DOCKER_REGISTRY}/microservice-public-web-revamp:latest
          docker tag public-web-revamp:latest ${DOCKER_REGISTRY}/microservice-public-web-revamp:${{ steps.get_version.outputs.VERSION }}
          
          # Push both tags
          docker push ${DOCKER_REGISTRY}/microservice-public-web-revamp:latest
          docker push ${DOCKER_REGISTRY}/microservice-public-web-revamp:${{ steps.get_version.outputs.VERSION }}
          
          # Update the ECS service to use the new deployment
          aws ecs update-service --cluster helios-cooperate-ecs-cluster --service public-web-revamp --force-new-deployment
